#!/bin/tcsh

if($#argv > 0)then
    set host = $argv[1]
else
    set host = ''
endif

switch ($host)
case "dio"
    rsync --progress -azu *.f90 -e ssh dio:simulation/PIC2D/src/shock/
    breaksw
case "hx600"
    rsync --progress -azu *.f90 -e ssh sp2:simulation/PIC2D/src/shock/
    breaksw
case "maja"
    rsync --progress -azu *.f90 -e ssh maja:simulation/PIC2D/src/shock/
    breaksw
case "xt"
    rsync --progress -azu *.f90 -e ssh xt:simulation/PIC2D/src/shock/
    breaksw
case "oak"
    rsync --progress -azu *.f90 -e ssh oak:simulation/PIC2D/src/shock/
    breaksw
default
    echo "choose dio or hx600 or maja or xt or oak"
endsw
