#!/bin/tcsh

if($#argv > 0)then
    set host = $argv[1]
else
    set host = ''
endif

switch ($host)
case "k"
    rsync --progress -azu *.f90 -e ssh k:simulation/PIC2D/src/shock/
    breaksw
case "xc"
    rsync --progress -azu *.f90 -e ssh xc:simulation/PIC2D/src/shock/
    breaksw
default
    echo "choose k or xc"
endsw
